#### laser_filters/scan_to_scan_filter_chain
#scan_filter_chain:
# - name: through
#   type: laser_filters/LaserScanRangeFilter
#   params: 
#     lower_threshold: 0.1
#     upper_threshold: 29.5
# - name: shadows
#   type: laser_filters/ScanShadowsFilter
#   params:
#     min_angle: 5
#     max_angle: 175
#     neighbors: 8
#     window: 1
# - name: dark_shadows
#   type: laser_filters/LaserScanIntensityFilter
#   params: 
#     lower_threshold: 100
#     upper_threshold: 10000
#     disp_histogram: 0
#### laser_scan_assembler
filters:
 - name: through
   type: laser_filters/LaserScanRangeFilter
   params: 
     lower_threshold: 0.4
     upper_threshold: 29.5
