#base_local_planner: "dwa_local_planner/DWAPlannerROS"
#
#DWAPlannerROS:
#  min_vel_x: -0.5
#  min_trans_vel: 0.1
#

TrajectoryPlannerROS:
  #Independent settings for the local costmap
  sim_time: 1.7
  sim_granularity: 0.025
  dwa: true
  vx_samples: 3
  vtheta_samples: 20
  max_vel_x: 1.25
  min_vel_x: 0.2
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.40
  xy_goal_tolerance: 0.16
  yaw_goal_tolerance: 0.12
  latch_xy_goal_tolerance: true
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05
  holonomic_robot: true
  acc_lim_th: 0.55
  acc_lim_x: 0.55
  acc_lim_y: 0.55
  backup_vel: -.5

