hrpsys_gazebo_configuration:
  robotname: HRP2JSK
  joint_id_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  joints:
    - RLEG_JOINT0
    - RLEG_JOINT1
    - RLEG_JOINT2
    - RLEG_JOINT3
    - RLEG_JOINT4
    - RLEG_JOINT5
    - LLEG_JOINT0
    - LLEG_JOINT1
    - LLEG_JOINT2
    - LLEG_JOINT3
    - LLEG_JOINT4
    - LLEG_JOINT5
    - CHEST_JOINT0
    - CHEST_JOINT1
    - HEAD_JOINT0
    - HEAD_JOINT1
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
    - RARM_JOINT6
    - RARM_JOINT7
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
    - LARM_JOINT6
    - LARM_JOINT7
  gains:
    CHEST_JOINT0: {p: 3000.0, d:   8.0, i: 0.0, i_clamp: 0.0}
    CHEST_JOINT1: {p: 1000.0, d:   4.0, i: 0.0, i_clamp: 0.0}
    HEAD_JOINT0:  {p:  150.0, d:   0.5, i: 0.0, i_clamp: 0.0}
    HEAD_JOINT1:  {p:  700.0, d:   1.5, i: 0.0, i_clamp: 0.0}
    LARM_JOINT0:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0}
    LARM_JOINT1:  {p: 1000.0, d:   2.0, i: 0.0, i_clamp: 0.0}
    LARM_JOINT2:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0}
    LARM_JOINT3:  {p: 1500.0, d:   3.0, i: 0.0, i_clamp: 0.0}
    LARM_JOINT4:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0}
    LARM_JOINT5:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0}
    LARM_JOINT6:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0}
    LARM_JOINT7:  {p:   20.0, d:  0.02, i: 0.0, i_clamp: 0.0}
    RARM_JOINT0:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0}
    RARM_JOINT1:  {p: 1000.0, d:   2.0, i: 0.0, i_clamp: 0.0}
    RARM_JOINT2:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0}
    RARM_JOINT3:  {p: 1500.0, d:   3.0, i: 0.0, i_clamp: 0.0}
    RARM_JOINT4:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0}
    RARM_JOINT5:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0}
    RARM_JOINT6:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0}
    RARM_JOINT7:  {p:   20.0, d:  0.02, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT0:  {p:  800.0, d:   2.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT1:  {p: 1200.0, d:   4.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT2:  {p: 3000.0, d:  15.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT3:  {p: 2500.0, d:  12.5, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT4:  {p: 2000.0, d:  10.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT5:  {p: 1000.0, d:   4.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT0:  {p:  800.0, d:   2.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT1:  {p: 1200.0, d:   4.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT2:  {p: 3000.0, d:  15.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT3:  {p: 2500.0, d:  12.5, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT4:  {p: 2000.0, d:  10.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT5:  {p: 1000.0, d:   2.0, i: 0.0, i_clamp: 0.0}
  force_torque_sensors:
    - lfsensor
    - rfsensor 
    - lhsensor
    - rhsensor 
  force_torque_sensors_config:
## TODO: add translation and rotation
    lfsensor: {joint_name: 'LLEG_JOINT5', frame_id: 'LLEG_LINK5'}
    rfsensor: {joint_name: 'RLEG_JOINT5', frame_id: 'RLEG_LINK5'}
    lhsensor: {joint_name: 'LARM_JOINT6', frame_id: 'LARM_LINK6'}
    rhsensor: {joint_name: 'RARM_JOINT6', frame_id: 'RARM_LINK6'}
  imu_sensors:
    - imu_sensor0
  imu_sensors_config:
## TODO: add translation and rotation
    imu_sensor0: {ros_name: 'waist_imu', link_name: 'CHEST_LINK1', frame_id: 'CHEST_LINK1'}
