controller_configuration:
  - group_name: larm
    controller_name: /larm_controller
    joint_list:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_P
      - L_WRIST_Y
      - L_WRIST_R
      - L_HAND_J0
      - L_HAND_J1
  - group_name: rarm
    controller_name: /rarm_controller
    joint_list:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_P
      - R_WRIST_Y
      - R_WRIST_R
      - R_HAND_J0
      - R_HAND_J1
  - group_name: head
    controller_name: /head_controller
    joint_list:
      - NECK_Y
      - NECK_R
      - NECK_P
  - group_name: torso
    controller_name: /torso_controller
    joint_list:
      - CHEST_P
      - CHEST_R
      - CHEST_Y
