min_sensor_dist: .25
self_see_default_padding: .025
self_see_default_scale: 1.0
self_see_links:
  - name: utorso
    padding: .04
  - name: l_clav
  - name: l_farm
  - name: l_foot
  - name: l_hand
  - name: l_larm
  - name: l_lglut
  - name: l_lleg
  - name: l_scap
  - name: l_talus
  - name: l_uarm
  - name: l_uglut
  - name: l_uleg
  - name: ltorso
  - name: mtorso
  - name: pelvis
  - name: r_clav
  - name: r_farm
  - name: r_foot
  - name: r_hand
  - name: r_larm
  - name: r_lglut
  - name: r_lleg
  - name: r_scap
  - name: r_talus
  - name: r_uarm
  - name: r_uglut
  - name: r_uleg
  - name: utorso
  - name: r_situational_awareness_camera_link
  - name: l_situational_awareness_camera_link
  - name: right_palm
  - name: right_f0_base
  - name: right_f0_fixed_accel
  - name: right_f0_0
  - name: right_f0_1
  - name: right_f0_1_accel
  - name: right_f0_2
  - name: right_f0_2_accel
  - name: right_f1_base
  - name: right_f1_fixed_accel
  - name: right_f1_0
  - name: right_f1_1
  - name: right_f1_1_accel
  - name: right_f1_2
  - name: right_f1_2_accel
  - name: right_f2_base
  - name: right_f2_fixed_accel
  - name: right_f2_0
  - name: right_f2_1
  - name: right_f2_1_accel
  - name: right_f2_2
  - name: right_f2_2_accel
  - name: right_f3_base
  - name: right_f3_fixed_accel
  - name: right_f3_0
  - name: right_f3_1
  - name: right_f3_1_accel
  - name: right_f3_2
  - name: right_f3_2_accel
  - name: right_palm_left_camera_frame
  - name: right_palm_right_camera_frame
  - name: left_palm
  - name: left_f0_base
  - name: left_f0_fixed_accel
  - name: left_f0_0
  - name: left_f0_1
  - name: left_f0_1_accel
  - name: left_f0_2
  - name: left_f0_2_accel
  - name: left_f1_base
  - name: left_f1_fixed_accel
  - name: left_f1_0
  - name: left_f1_1
  - name: left_f1_1_accel
  - name: left_f1_2
  - name: left_f1_2_accel
  - name: left_f2_base
  - name: left_f2_fixed_accel
  - name: left_f2_0
  - name: left_f2_1
  - name: left_f2_1_accel
  - name: left_f2_2
  - name: left_f2_2_accel
  - name: left_f3_base
  - name: left_f3_fixed_accel
  - name: left_f3_0
  - name: left_f3_1
  - name: left_f3_1_accel
  - name: left_f3_2
  - name: left_f3_2_accel
  - name: left_palm_left_camera_frame
  - name: left_palm_right_camera_frame
  - name: imu_link
  - name: head
  - name: hokuyo_link
  - name: head_hokuyo_frame
  - name: left_camera_frame
  - name: right_camera_frame
  - name: center_top_led_frame
  - name: center_bottom_led_frame
  - name: left_led_frame
  - name: right_led_frame
  - name: head_imu_link
