#include <ExtendedDataTypes.idl>

interface ArmMotionService
{
    typedef sequence<double> DblSequence;
    boolean MoveArm(in RTC::Pose3D goal, in double handWidth, 
		    in string arm, in boolean useTorso, in boolean checkCollision);
    // boolean MoveArm(in RTC::Pose3D goal, in DblSequence handJointAngles, 
    // 		    in string arm, in boolean useTorso, in boolean checkCollision);
};
