module OpenHRP
{
  interface StateHolderService
  {
    typedef sequence<double> DblSequence;

    /**
     * @brief output current joint angles as reference joint angles
     */
    void goActual();

    struct Command{
      DblSequence jointRefs;
      DblSequence baseTransform;
    };

    void getCommand(out Command com);
  };
};
