# DO NOT EDIT THIS FILE!
#
# Python module _GlobalIDL__POA generated by omniidl

import omniORB
omniORB.updateModule("_GlobalIDL__POA")

# ** 1. Stub files contributing to this module
import RobotHardwareService_idl
import SequencePlayerService_idl
import VideoStreamService_idl
import ArmMotion_idl
import GraspController_idl

# ** 2. Sub-modules

# ** 3. End
