# Python stubs generated by omniidl from ArmMotion.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"ArmMotion.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"ArmMotion.idl")

# #include "BasicDataType.idl"
import BasicDataType_idl
_0_RTC = omniORB.openModule("RTC")
_0_RTC__POA = omniORB.openModule("RTC__POA")
# #include "ExtendedDataTypes.idl"
import ExtendedDataTypes_idl
_0_RTC = omniORB.openModule("RTC")
_0_RTC__POA = omniORB.openModule("RTC__POA")

# interface ArmMotionService
_0__GlobalIDL._d_ArmMotionService = (omniORB.tcInternal.tv_objref, "IDL:ArmMotionService:1.0", "ArmMotionService")
omniORB.typeMapping["IDL:ArmMotionService:1.0"] = _0__GlobalIDL._d_ArmMotionService
_0__GlobalIDL.ArmMotionService = omniORB.newEmptyClass()
class ArmMotionService :
    _NP_RepositoryId = _0__GlobalIDL._d_ArmMotionService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    
    # typedef ... DblSequence
    class DblSequence:
        _NP_RepositoryId = "IDL:ArmMotionService/DblSequence:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_DblSequence  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0)
    _ad_DblSequence = (omniORB.tcInternal.tv_alias, DblSequence._NP_RepositoryId, "DblSequence", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0))
    _tc_DblSequence = omniORB.tcInternal.createTypeCode(_ad_DblSequence)
    omniORB.registerType(DblSequence._NP_RepositoryId, _ad_DblSequence, _tc_DblSequence)


_0__GlobalIDL.ArmMotionService = ArmMotionService
_0__GlobalIDL._tc_ArmMotionService = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_ArmMotionService)
omniORB.registerType(ArmMotionService._NP_RepositoryId, _0__GlobalIDL._d_ArmMotionService, _0__GlobalIDL._tc_ArmMotionService)

# ArmMotionService operations and attributes
ArmMotionService._d_MoveArm = ((omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], omniORB.tcInternal.tv_double, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean, omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_MoveArm2 = ((omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], omniORB.tcInternal.tv_double, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_Grab = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_Release = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_Move = ((omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_MoveArmRelative = ((omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], omniORB.tcInternal.tv_double, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean, omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_GoPreparePose = ((), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_GetJointAngles = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)
ArmMotionService._d_Fk = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)
ArmMotionService._d_Ik = ((omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)
ArmMotionService._d_AddObject = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"]), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_DeleteObject = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
ArmMotionService._d_ResetWorld = ((), (), None)
ArmMotionService._d_GraspPlan = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], omniORB.tcInternal.tv_boolean), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)
ArmMotionService._d_RequestNext = ((omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], omniORB.tcInternal.tv_double), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)
ArmMotionService._d_PlacePlan = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"]), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)
ArmMotionService._d_RecognizeParts = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)
ArmMotionService._d_RecognizePocket = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ArmMotionService/DblSequence:1.0"], ), None)

# ArmMotionService object reference
class _objref_ArmMotionService (CORBA.Object):
    _NP_RepositoryId = ArmMotionService._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def MoveArm(self, *args):
        return _omnipy.invoke(self, "MoveArm", _0__GlobalIDL.ArmMotionService._d_MoveArm, args)

    def MoveArm2(self, *args):
        return _omnipy.invoke(self, "MoveArm2", _0__GlobalIDL.ArmMotionService._d_MoveArm2, args)

    def Grab(self, *args):
        return _omnipy.invoke(self, "Grab", _0__GlobalIDL.ArmMotionService._d_Grab, args)

    def Release(self, *args):
        return _omnipy.invoke(self, "Release", _0__GlobalIDL.ArmMotionService._d_Release, args)

    def Move(self, *args):
        return _omnipy.invoke(self, "Move", _0__GlobalIDL.ArmMotionService._d_Move, args)

    def MoveArmRelative(self, *args):
        return _omnipy.invoke(self, "MoveArmRelative", _0__GlobalIDL.ArmMotionService._d_MoveArmRelative, args)

    def GoPreparePose(self, *args):
        return _omnipy.invoke(self, "GoPreparePose", _0__GlobalIDL.ArmMotionService._d_GoPreparePose, args)

    def GetJointAngles(self, *args):
        return _omnipy.invoke(self, "GetJointAngles", _0__GlobalIDL.ArmMotionService._d_GetJointAngles, args)

    def Fk(self, *args):
        return _omnipy.invoke(self, "Fk", _0__GlobalIDL.ArmMotionService._d_Fk, args)

    def Ik(self, *args):
        return _omnipy.invoke(self, "Ik", _0__GlobalIDL.ArmMotionService._d_Ik, args)

    def AddObject(self, *args):
        return _omnipy.invoke(self, "AddObject", _0__GlobalIDL.ArmMotionService._d_AddObject, args)

    def DeleteObject(self, *args):
        return _omnipy.invoke(self, "DeleteObject", _0__GlobalIDL.ArmMotionService._d_DeleteObject, args)

    def ResetWorld(self, *args):
        return _omnipy.invoke(self, "ResetWorld", _0__GlobalIDL.ArmMotionService._d_ResetWorld, args)

    def GraspPlan(self, *args):
        return _omnipy.invoke(self, "GraspPlan", _0__GlobalIDL.ArmMotionService._d_GraspPlan, args)

    def RequestNext(self, *args):
        return _omnipy.invoke(self, "RequestNext", _0__GlobalIDL.ArmMotionService._d_RequestNext, args)

    def PlacePlan(self, *args):
        return _omnipy.invoke(self, "PlacePlan", _0__GlobalIDL.ArmMotionService._d_PlacePlan, args)

    def RecognizeParts(self, *args):
        return _omnipy.invoke(self, "RecognizeParts", _0__GlobalIDL.ArmMotionService._d_RecognizeParts, args)

    def RecognizePocket(self, *args):
        return _omnipy.invoke(self, "RecognizePocket", _0__GlobalIDL.ArmMotionService._d_RecognizePocket, args)

    __methods__ = ["MoveArm", "MoveArm2", "Grab", "Release", "Move", "MoveArmRelative", "GoPreparePose", "GetJointAngles", "Fk", "Ik", "AddObject", "DeleteObject", "ResetWorld", "GraspPlan", "RequestNext", "PlacePlan", "RecognizeParts", "RecognizePocket"] + CORBA.Object.__methods__

omniORB.registerObjref(ArmMotionService._NP_RepositoryId, _objref_ArmMotionService)
_0__GlobalIDL._objref_ArmMotionService = _objref_ArmMotionService
del ArmMotionService, _objref_ArmMotionService

# ArmMotionService skeleton
__name__ = "_GlobalIDL__POA"
class ArmMotionService (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.ArmMotionService._NP_RepositoryId


    _omni_op_d = {"MoveArm": _0__GlobalIDL.ArmMotionService._d_MoveArm, "MoveArm2": _0__GlobalIDL.ArmMotionService._d_MoveArm2, "Grab": _0__GlobalIDL.ArmMotionService._d_Grab, "Release": _0__GlobalIDL.ArmMotionService._d_Release, "Move": _0__GlobalIDL.ArmMotionService._d_Move, "MoveArmRelative": _0__GlobalIDL.ArmMotionService._d_MoveArmRelative, "GoPreparePose": _0__GlobalIDL.ArmMotionService._d_GoPreparePose, "GetJointAngles": _0__GlobalIDL.ArmMotionService._d_GetJointAngles, "Fk": _0__GlobalIDL.ArmMotionService._d_Fk, "Ik": _0__GlobalIDL.ArmMotionService._d_Ik, "AddObject": _0__GlobalIDL.ArmMotionService._d_AddObject, "DeleteObject": _0__GlobalIDL.ArmMotionService._d_DeleteObject, "ResetWorld": _0__GlobalIDL.ArmMotionService._d_ResetWorld, "GraspPlan": _0__GlobalIDL.ArmMotionService._d_GraspPlan, "RequestNext": _0__GlobalIDL.ArmMotionService._d_RequestNext, "PlacePlan": _0__GlobalIDL.ArmMotionService._d_PlacePlan, "RecognizeParts": _0__GlobalIDL.ArmMotionService._d_RecognizeParts, "RecognizePocket": _0__GlobalIDL.ArmMotionService._d_RecognizePocket}

ArmMotionService._omni_skeleton = ArmMotionService
_0__GlobalIDL__POA.ArmMotionService = ArmMotionService
omniORB.registerSkeleton(ArmMotionService._NP_RepositoryId, ArmMotionService)
del ArmMotionService
__name__ = "_GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "ArmMotion_idl"

_exported_modules = ( "_GlobalIDL", )

# The end.
