# Python stubs generated by omniidl from GraspController.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"GraspController.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"GraspController.idl")


# interface GraspPlanStart
_0__GlobalIDL._d_GraspPlanStart = (omniORB.tcInternal.tv_objref, "IDL:GraspPlanStart:1.0", "GraspPlanStart")
omniORB.typeMapping["IDL:GraspPlanStart:1.0"] = _0__GlobalIDL._d_GraspPlanStart
_0__GlobalIDL.GraspPlanStart = omniORB.newEmptyClass()
class GraspPlanStart :
    _NP_RepositoryId = _0__GlobalIDL._d_GraspPlanStart[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    
    # typedef ... DblSequence3
    class DblSequence3:
        _NP_RepositoryId = "IDL:GraspPlanStart/DblSequence3:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_DblSequence3  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 3)
    _ad_DblSequence3 = (omniORB.tcInternal.tv_alias, DblSequence3._NP_RepositoryId, "DblSequence3", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 3))
    _tc_DblSequence3 = omniORB.tcInternal.createTypeCode(_ad_DblSequence3)
    omniORB.registerType(DblSequence3._NP_RepositoryId, _ad_DblSequence3, _tc_DblSequence3)
    
    # typedef ... DblSequence9
    class DblSequence9:
        _NP_RepositoryId = "IDL:GraspPlanStart/DblSequence9:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_DblSequence9  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 9)
    _ad_DblSequence9 = (omniORB.tcInternal.tv_alias, DblSequence9._NP_RepositoryId, "DblSequence9", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 9))
    _tc_DblSequence9 = omniORB.tcInternal.createTypeCode(_ad_DblSequence9)
    omniORB.registerType(DblSequence9._NP_RepositoryId, _ad_DblSequence9, _tc_DblSequence9)


_0__GlobalIDL.GraspPlanStart = GraspPlanStart
_0__GlobalIDL._tc_GraspPlanStart = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_GraspPlanStart)
omniORB.registerType(GraspPlanStart._NP_RepositoryId, _0__GlobalIDL._d_GraspPlanStart, _0__GlobalIDL._tc_GraspPlanStart)

# GraspPlanStart operations and attributes
GraspPlanStart._d_GraspPlanningStart = ((omniORB.tcInternal.tv_ulong, omniORB.typeMapping["IDL:GraspPlanStart/DblSequence3:1.0"], omniORB.typeMapping["IDL:GraspPlanStart/DblSequence9:1.0"]), (omniORB.tcInternal.tv_ulong, ), None)
GraspPlanStart._d_ReleasePlanningStart = ((omniORB.tcInternal.tv_ulong, omniORB.typeMapping["IDL:GraspPlanStart/DblSequence3:1.0"], omniORB.typeMapping["IDL:GraspPlanStart/DblSequence9:1.0"]), (omniORB.tcInternal.tv_ulong, ), None)

# GraspPlanStart object reference
class _objref_GraspPlanStart (CORBA.Object):
    _NP_RepositoryId = GraspPlanStart._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def GraspPlanningStart(self, *args):
        return _omnipy.invoke(self, "GraspPlanningStart", _0__GlobalIDL.GraspPlanStart._d_GraspPlanningStart, args)

    def ReleasePlanningStart(self, *args):
        return _omnipy.invoke(self, "ReleasePlanningStart", _0__GlobalIDL.GraspPlanStart._d_ReleasePlanningStart, args)

    __methods__ = ["GraspPlanningStart", "ReleasePlanningStart"] + CORBA.Object.__methods__

omniORB.registerObjref(GraspPlanStart._NP_RepositoryId, _objref_GraspPlanStart)
_0__GlobalIDL._objref_GraspPlanStart = _objref_GraspPlanStart
del GraspPlanStart, _objref_GraspPlanStart

# GraspPlanStart skeleton
__name__ = "_GlobalIDL__POA"
class GraspPlanStart (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.GraspPlanStart._NP_RepositoryId


    _omni_op_d = {"GraspPlanningStart": _0__GlobalIDL.GraspPlanStart._d_GraspPlanningStart, "ReleasePlanningStart": _0__GlobalIDL.GraspPlanStart._d_ReleasePlanningStart}

GraspPlanStart._omni_skeleton = GraspPlanStart
_0__GlobalIDL__POA.GraspPlanStart = GraspPlanStart
omniORB.registerSkeleton(GraspPlanStart._NP_RepositoryId, GraspPlanStart)
del GraspPlanStart
__name__ = "_GlobalIDL"

# interface GraspPlanResult
_0__GlobalIDL._d_GraspPlanResult = (omniORB.tcInternal.tv_objref, "IDL:GraspPlanResult:1.0", "GraspPlanResult")
omniORB.typeMapping["IDL:GraspPlanResult:1.0"] = _0__GlobalIDL._d_GraspPlanResult
_0__GlobalIDL.GraspPlanResult = omniORB.newEmptyClass()
class GraspPlanResult :
    _NP_RepositoryId = _0__GlobalIDL._d_GraspPlanResult[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    
    # typedef ... DblSequence3
    class DblSequence3:
        _NP_RepositoryId = "IDL:GraspPlanResult/DblSequence3:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_DblSequence3  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 3)
    _ad_DblSequence3 = (omniORB.tcInternal.tv_alias, DblSequence3._NP_RepositoryId, "DblSequence3", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 3))
    _tc_DblSequence3 = omniORB.tcInternal.createTypeCode(_ad_DblSequence3)
    omniORB.registerType(DblSequence3._NP_RepositoryId, _ad_DblSequence3, _tc_DblSequence3)
    
    # typedef ... DblSequence9
    class DblSequence9:
        _NP_RepositoryId = "IDL:GraspPlanResult/DblSequence9:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_DblSequence9  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 9)
    _ad_DblSequence9 = (omniORB.tcInternal.tv_alias, DblSequence9._NP_RepositoryId, "DblSequence9", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 9))
    _tc_DblSequence9 = omniORB.tcInternal.createTypeCode(_ad_DblSequence9)
    omniORB.registerType(DblSequence9._NP_RepositoryId, _ad_DblSequence9, _tc_DblSequence9)


_0__GlobalIDL.GraspPlanResult = GraspPlanResult
_0__GlobalIDL._tc_GraspPlanResult = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_GraspPlanResult)
omniORB.registerType(GraspPlanResult._NP_RepositoryId, _0__GlobalIDL._d_GraspPlanResult, _0__GlobalIDL._tc_GraspPlanResult)

# GraspPlanResult operations and attributes
GraspPlanResult._d_GraspPlanningResult = ((omniORB.typeMapping["IDL:GraspPlanResult/DblSequence3:1.0"], omniORB.typeMapping["IDL:GraspPlanResult/DblSequence9:1.0"], omniORB.typeMapping["IDL:GraspPlanResult/DblSequence3:1.0"], omniORB.typeMapping["IDL:GraspPlanResult/DblSequence9:1.0"], omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_ulong), (omniORB.tcInternal.tv_ulong, ), None)
GraspPlanResult._d_ReleasePlanningResult = ((omniORB.typeMapping["IDL:GraspPlanResult/DblSequence3:1.0"], omniORB.typeMapping["IDL:GraspPlanResult/DblSequence9:1.0"], omniORB.typeMapping["IDL:GraspPlanResult/DblSequence3:1.0"], omniORB.typeMapping["IDL:GraspPlanResult/DblSequence9:1.0"], omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_ulong), (omniORB.tcInternal.tv_ulong, ), None)

# GraspPlanResult object reference
class _objref_GraspPlanResult (CORBA.Object):
    _NP_RepositoryId = GraspPlanResult._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def GraspPlanningResult(self, *args):
        return _omnipy.invoke(self, "GraspPlanningResult", _0__GlobalIDL.GraspPlanResult._d_GraspPlanningResult, args)

    def ReleasePlanningResult(self, *args):
        return _omnipy.invoke(self, "ReleasePlanningResult", _0__GlobalIDL.GraspPlanResult._d_ReleasePlanningResult, args)

    __methods__ = ["GraspPlanningResult", "ReleasePlanningResult"] + CORBA.Object.__methods__

omniORB.registerObjref(GraspPlanResult._NP_RepositoryId, _objref_GraspPlanResult)
_0__GlobalIDL._objref_GraspPlanResult = _objref_GraspPlanResult
del GraspPlanResult, _objref_GraspPlanResult

# GraspPlanResult skeleton
__name__ = "_GlobalIDL__POA"
class GraspPlanResult (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.GraspPlanResult._NP_RepositoryId


    _omni_op_d = {"GraspPlanningResult": _0__GlobalIDL.GraspPlanResult._d_GraspPlanningResult, "ReleasePlanningResult": _0__GlobalIDL.GraspPlanResult._d_ReleasePlanningResult}

GraspPlanResult._omni_skeleton = GraspPlanResult
_0__GlobalIDL__POA.GraspPlanResult = GraspPlanResult
omniORB.registerSkeleton(GraspPlanResult._NP_RepositoryId, GraspPlanResult)
del GraspPlanResult
__name__ = "_GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "GraspController_idl"

_exported_modules = ( "_GlobalIDL", )

# The end.
