# Python stubs generated by omniidl from JointDataTypes.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "BasicDataType.idl"
import BasicDataType_idl
_0_RTC = omniORB.openModule("RTC")
_0_RTC__POA = omniORB.openModule("RTC__POA")

#
# Start of module "RTC"
#
__name__ = "RTC"
_0_RTC = omniORB.openModule("RTC", r"JointDataTypes.idl")
_0_RTC__POA = omniORB.openModule("RTC__POA", r"JointDataTypes.idl")

_0_RTC.servoON = 1
_0_RTC.emergencyStop = 2
_0_RTC.protectiveStopLower = 4
_0_RTC.protectiveStopUpper = 8

# struct TimedJointData
_0_RTC.TimedJointData = omniORB.newEmptyClass()
class TimedJointData (omniORB.StructBase):
    _NP_RepositoryId = "IDL:RTC/TimedJointData:1.0"

    def __init__(self, tm, cmd, id, qCommand, qState, dqState, servoCommand, servoState, collisionFlag):
        self.tm = tm
        self.cmd = cmd
        self.id = id
        self.qCommand = qCommand
        self.qState = qState
        self.dqState = dqState
        self.servoCommand = servoCommand
        self.servoState = servoState
        self.collisionFlag = collisionFlag

_0_RTC.TimedJointData = TimedJointData
_0_RTC._d_TimedJointData  = (omniORB.tcInternal.tv_struct, TimedJointData, TimedJointData._NP_RepositoryId, "TimedJointData", "tm", omniORB.typeMapping["IDL:RTC/Time:1.0"], "cmd", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:RTC/Time:1.0"], 0), "id", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_octet, 0), "qCommand", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0), 0), "qState", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0), 0), "dqState", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0), 0), "servoCommand", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_octet, 0), "servoState", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_octet, 0), "collisionFlag", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_octet, 0))
_0_RTC._tc_TimedJointData = omniORB.tcInternal.createTypeCode(_0_RTC._d_TimedJointData)
omniORB.registerType(TimedJointData._NP_RepositoryId, _0_RTC._d_TimedJointData, _0_RTC._tc_TimedJointData)
del TimedJointData

#
# End of module "RTC"
#
__name__ = "JointDataTypes_idl"

_exported_modules = ( "RTC", )

# The end.
